scene_path: data/living-room/scene.xml
resolution:
  width: 512
  height: 512
initial_samples: 16                 # number of initial 1spp images
initial_spp: 1                      # SPP for initial render
extra_samples: 16                   # number of extra images to sample adaptively
extra_spp: 4                        # SPP for each extra image
quantile_threshold: 0.8             # quantile to decide which pixels get more samples
histogram_bins: 16                  # bins for computing histograms per pixel
seed_start: 0                       # random seed base for reproducibility
debug: true                         # print intermediate info
mode: 'stat'                        # 'stat' is using mean/var or 'hist' if using predicted map from hist distribution

dataset:
  root_dir: output                        # Raw dataset location
  cached_dir: crops                       # Cached histograms are saved
  crop_size: 128
  crops_per_scene: 150                    # num of crops per scene to generate
  use_cached_crops: false
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: stat                              # 'hist' for full distribution or 'stat' for mean/var only
  data_augmentation: true                 # horizontal and vertical flips
  clean: true                             # Whether to include 'clean' targets if available
  aov: true                               # Whether to include 'aov' channels to input image (note: model in_channels is 9 if aov is true)
  debug: true                             # if true saves one plot per epoch in a debug plot folder
  supervised: false                       # if true supervised else self supervised
  tonemap: none                           # tonemap applied to the loss: 'log' or 'reinhard' or 'reinhard_gamma' or 'none' 
  input_tonemap: none                     # tonemap applied to the input: 'log' or 'reinhard' or 'reinhard_gamma' or 'none' 
  target_split: 16

model:
  model_name: n2n                       # 'gap' or 'n2n'
  in_channels: 10                       # 3 (img) or 9 (img + aov) or 10 (stat + aov)
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 4                              # only for GAP model
  start_filters: 48                     # only for GAP model
  learning_rate: 1e-4

# DATALOADER
batch_size: 12                          # minibatch: 8, 12, or 16
num_workers: 4                          # 4 on CPU or 8 on GPU
shuffle: true
pin_memory: false
loss: mse                               # 'mse' or 'l1'

val_split: 0.1                          # 10% validation split

# TRAINING
num_epochs: 100
plot_every: 10                           # how often to save the debug plots
save_dir: checkpoints