# General settings
batch_size: 32
num_workers: 4
shuffle: false

out_mode: mean                          # 'mean' or 'dist'   
target_samples: 3                       # Number of samples to use for the target histogram            

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: hist                            # Options: 'hist' for hist2noise or 'img' for noise2noise
  data_augmentation: false
  virt_size: 1000
  clean: true                           # Whether to include 'clean' targets if available
  debug: false
