# General settings
batch_size: 32
num_workers: 4
shuffle: false           

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: img                             # Options: 'hist' for hist2noise or 'img' for noise2noise
  data_augmentation: true
  virt_size: 100
  clean: true                           # Whether to include 'clean' targets if available
  aov: true                             # Whether to include 'aov' channels to input image (note: model in_channels is 9 if aov is true)
  debug: true
  supervised: false                     # if true supervised else self supervised
  tonemap: none                         # 'log' or 'reinhard' or 'reinhard_gamma' or 'none'
  target_split: 16