# Evaluation Parameters
eval:
  # idx: 27              # Sample index to evaluate
  n_eval_samples: 10
  hist_checkpoint: checkpoints/2025-07-21_hist2noise_mean_bins16.pth
  img_checkpoint: checkpoints/2025-07-22_noise2noise_mean_binsimg.pth

model:
  in_channels: 3
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 3
  start_filters: 32
  learning_rate: 1e-4

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  data_augmentation: false
  virt_size: 100
  clean: true
  debug: false
