# Evaluation Parameters
model_path: checkpoints/20250718_hist2hist_dist.pth

model:
  in_channels: 3
  out_mode: dist                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 3
  start_filters: 32
  learning_rate: 1e-4

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: hist                            # Options: 'hist' for hist2hist
  data_augmentation: true
  virt_size: 100
  clean: true                           # Whether to include 'clean' targets if available
  debug: true
  hist_regeneration: false
