eval:
  # idx: 27              # Sample index to evaluate
  n_eval_samples: 10
  hist_checkpoint: results/n2n/2025-07-27_noise2noise_mean_binsimg_ep100_mse_aov.pth
  img_checkpoint: results/n2n/2025-07-27_noise2noise_mean_binsimg_ep100_mse.pth

model:
  model_name: n2n                       # 'gap' or 'n2n'
  in_channels: 3                        # 9 if using AOV else 3
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 4                              # only for GAP model
  start_filters: 48  
  learning_rate: 1e-4

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: img
  data_augmentation: false
  virt_size: 100
  clean: true
  aov: true
  debug: false
  hist_regeneration: false
  supervised: false
  tonemap: none                         # 'log' or 'reinhard' or 'none'
  target_split: 16

batch_size: 16
num_workers: 4
shuffle: true
pin_memory: false
