# Evaluation Parameters
eval:
  # idx: 27              # Sample index to evaluate
  n_eval_samples: 10
  hist_checkpoint: checkpoints/2025-07-26_noise2noise_mean_binsimg_ep20_lhdr.pth
  img_checkpoint: checkpoints/2025-07-26_noise2noise_mean_binsimg_ep20_lhdr.pth

model:
  in_channels: 3
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 4
  start_filters: 48
  learning_rate: 1e-4

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  data_augmentation: false
  virt_size: 100
  clean: true
  debug: false
  supervised: false
  tonemap: none                         # 'log' or 'reinhard' or 'none'
  hist_regeneration: false

# Additional runtime and corruption settings
data: ../data                             # Dataset root path
load_ckpt: ./../ckpts/mc-1759/n2n-epoch64-0.21617.pt                           # Path to load checkpoint (set to null if unused)
show_output: 5                            # Pop up window to display outputs
cuda: true                                # Use CUDA if available

noise_type: gaussian                      # ['gaussian', 'poisson', 'text', 'mc']
noise_param: 50.0                         # e.g., sigma for Gaussian
seed: null                                # Random seed (optional)
crop_size: 256                            # Image crop size (note: overrides dataset.crop_size if used)

batch_size: 4
num_workers: 4
shuffle: true
pin_memory: false