# Evaluation Parameters
eval:
  idx: 51              # Sample index to evaluate
  seed: 42             # Seed for consistent shuffling and cropping
  hist_checkpoint: checkpoints/2025-07-15_128_hist2noise_mean_bins16.pth
  img_checkpoint: checkpoints/2025-07-15_128_noise2noise_mean_binsimg.pth

# Dataset 
dataset:
  root_dir: output
  cached_dir: histograms
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  data_augmentation: false
  virt_size: 100
  clean: true
  debug: false
