# Evaluation Parameters
model_path: results/h2h/20250729_hist2hist_dist_20ep_crop.pth
num_workers: 4
num_samples: 10       # number of images to test during the evaluate step
num_steps: 10         # number of iterations to perform during generative accumulation of radiance
gen_mode: img         # 'img' for probability of radiance across image or 'res' for residual probability

model:
  model_name: gap
  in_channels: 3
  out_mode: dist                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 3
  start_filters: 32
  learning_rate: 1e-4

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: hist                            # Options: 'hist' for hist2hist
  data_augmentation: true
  virt_size: 100
  clean: true                           # Whether to include 'clean' targets if available
  debug: false
  target_sample: 20
  hist_regeneration: false

# General DataLoader settings
batch_size: 16
shuffle: true
pin_memory: false
