# Evaluation Parameters
eval:
  idx: 32              # Sample index to evaluate
  hist_checkpoint: checkpoints/2025-07-17_128_hist2noise_mean_bins16.pth
  img_checkpoint: checkpoints/2025-07-17_128_noise2noise_mean_binsimg.pth

model:
  in_channels: 3
  out_mode: mean                        # 'mean' or 'distribution'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 3
  start_filters: 32
  learning_rate: 1e-4
  weight_decay: 1e-5

# Dataset 
dataset:
  root_dir: output
  cached_dir: histograms
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  data_augmentation: false
  virt_size: 100
  clean: true
  debug: false
