# Evaluation Parameters
model_path: results/h2h/20250801_hist2hist_dist_100ep_nostat_crop.pth
num_workers: 4
num_samples: 3          # number of images to test during the evaluate step
num_steps: 100          # number of iterations to perform during generative accumulation of radiance
gen_mode: img           # 'img' for probability of radiance across image or 'res' for residual probability
plot_every: 10          # how oftern to plot the image

model:
  model_name: gap
  in_channels: 3                        # 3 by default
  n_bins_input: 16                      # hist_bins if only using hist, else 18 if using other stats
  out_mode: dist                        # 'mean' or 'dist' to output RGB image or distrbution
  merge_mode: concat                    # 'add' or 'concat'
  depth: 5                              # number of encoder/decoder blocks
  start_filters: 32
  learning_rate: 1e-4

dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: hist                            # Options: 'hist' for hist2hist
  data_augmentation: true               # random horizontal/vertical flips
  virt_size: 100                        # number of crops to generate across all the scenes
  clean: true                           # whether to include 'clean' targets if available
  debug: true                           # saves plot to output save_dir for debugging
  stat: false                           # wether to include mean and var value alongside histogram (helps with colour reconstruction)
  hist_regeneration: false
  target_sample: 16       

# DATALOADER
batch_size: 16
num_workers: 4
shuffle: true
pin_memory: false
crop: false                             # whether to compute bin edges per crop or per image  
start_from: empty                       # whether to start generating from an empty image or a noisy one
