title: "Model Predcitions"
entries:
  - path: "results/loss_test_img/hdr_mse/2025-08-06_noise2noise_mean_binsimg_ep300_mse.pth"
    loss_type: "MSE"
    tone_mapping: "HDR"

  - path: "results/loss_test_img/hdr_l1/2025-08-06_noise2noise_mean_binsimg_ep300_l1.pth"
    loss_type: "L1"
    tone_mapping: "HDR"

  - path: "results/loss_test_img/log_smape/2025-08-06_noise2noise_mean_binsimg_ep300_smape.pth"
    loss_type: "SMAPE"
    tone_mapping: "Log"

  - path: "results/loss_test_img/log_mse/2025-08-06_noise2noise_mean_binsimg_ep300_mse.pth"
    loss_type: "MSE"
    tone_mapping: "Log"

  - path: "results/loss_test_img/log_rmse/2025-08-06_noise2noise_mean_binsimg_ep300_root_mse.pth"
    loss_type: "RMSE"
    tone_mapping: "Log"

  - path: "results/loss_test_img/log_l1/2025-08-06_noise2noise_mean_binsimg_ep300_l1.pth"
    loss_type: "L1"
    tone_mapping: "Log"

  - path: "results/loss_test_img/reinhard_smape/2025-08-06_noise2noise_mean_binsimg_ep300_smape.pth"
    loss_type: "SMAPE"
    tone_mapping: "Reinhard"

  - path: "results/loss_test_img/reinhard_rmse/2025-08-06_noise2noise_mean_binsimg_ep300_root_mse.pth"
    loss_type: "RMSE"
    tone_mapping: "Reinhard"

dataset:
  root_dir: output                        # Raw dataset location
  cached_dir: crops                       # Cached histograms are saved
  crop_size: 128
  crops_per_scene: 300                    # num of crops per scene to generate
  use_cached_crops: true
  low_spp: 64
  high_spp: 4500
  hist_bins: 32
  mode: img                               # 'hist' for hist2noise or 'img' or 'stat' for noise2noise
  data_augmentation: true                 # horizontal and vertical flips
  clean: true                             # Whether to include 'clean' targets if available
  aov: true                               # Whether to include 'aov' channels to input image (note: model in_channels is 9 if aov is true)
  debug: true                             # if true saves one plot per epoch in a debug plot folder
  supervised: false                       # if true supervised else self supervised
  tonemap: none                           # tonemap applied to the loss: 'log' or 'reinhard' or 'reinhard_gamma' or 'none' 
  input_tonemap: log                      # tonemap applied to the input: 'log' or 'reinhard' or 'reinhard_gamma' or 'none' 
  target_split: 32

model:
  model_name: n2n                       # 'gap' or 'n2n'
  in_channels: 9                        # 3 (img) or 9 (img + aov) or 10 (stat + aov)
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 4                              # only for GAP model
  start_filters: 48                     # only for GAP model
  learning_rate: 1e-4
