groups:
  - title: "Image Loss Curves"
    entries:
      - path: "results/loss_test_img/log_smape/2025-08-06_img_loss_plot.npz"
        loss_type: "SMAPE"
        tone_mapping: "Log"

      # - path: "results/loss_test_img/log_mse/2025-08-06_img_loss_plot.npz"
      #   loss_type: "MSE"
      #   tone_mapping: "Log"

      - path: "results/loss_test_img/log_rmse/2025-08-06_img_loss_plot.npz"
        loss_type: "RMSE"
        tone_mapping: "Log"

      # - path: "results/loss_test/reinhard_smape/2025-08-06_img_loss_plot.npz"
      #   loss_type: "SMAPE"
      #   tone_mapping: "Reinhard"

      # - path: "results/loss_test_img/reinhard_mse/2025-08-06_img_loss_plot.npz"
      #   loss_type: "MSE"
      #   tone_mapping: "Reinhard"

      # - path: "results/loss_test_img/reinhard_rmse/2025-08-06_img_loss_plot.npz"
      #   loss_type: "RMSE"
      #   tone_mapping: "Reinhard"

  - title: "PSNR Curves"
    entries:
      - path: "results/loss_test_img/log_smape/2025-08-06_img_psnr_plot.npz"
        loss_type: "SMAPE"
        tone_mapping: "Log"

      # - path: "results/loss_test_img/log_mse/2025-08-06_img_psnr_plot.npz"
      #   loss_type: "MSE"
      #   tone_mapping: "Log"

      - path: "results/loss_test_img/log_rmse/2025-08-06_img_psnr_plot.npz"
        loss_type: "RMSE"
        tone_mapping: "Log"

      # - path: "results/loss_test/reinhard_smape/2025-08-06_img_psnr_plot.npz"
      #   loss_type: "SMAPE"
      #   tone_mapping: "Reinhard"

      # - path: "results/loss_test_img/reinhard_mse/2025-08-06_img_psnr_plot.npz"
      #   loss_type: "MSE"
      #   tone_mapping: "Reinhard"

      # - path: "results/loss_test_img/reinhard_rmse/2025-08-06_img_psnr_plot.npz"
      #   loss_type: "RMSE"
      #   tone_mapping: "Reinhard"
