dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: hist                            # Options: 'hist' for hist2hist
  data_augmentation: true
  virt_size: 1000
  clean: true                           # Whether to include 'clean' targets if available
  debug: false
  hist_regeneration: true
  target_sample: 16

model:
  model_name: gap
  in_channels: 3
  out_mode: dist                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 3
  start_filters: 32
  learning_rate: 1e-4

# General DataLoader settings
batch_size: 16
num_workers: 4
shuffle: true
pin_memory: false

val_split: 0.1  # 10% validation split

# training
num_epochs: 20
save_dir: checkpoints
