dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 256
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: img                        # Options: 'hist' for hist2noise or 'img' for noise2noise
  data_augmentation: true
  virt_size: 1000
  clean: true                       # Whether to include 'clean' targets if available

model:
  in_channels: 3
  out_mode: mean        # 'mean' or 'distribution'
  merge_mode: concat    # 'add' or 'concat'
  depth: 3
  start_filters: 64
  learning_rate: 1e-4
  weight_decay: 1e-5 

# General DataLoader settings
batch_size: 32
num_workers: 4
shuffle: true

val_split: 0.2  # 2% validation split

# training
num_epochs: 10
save_path: checkpoints/hist2noise.pth # change to include other params in the name!!!
