dataset:
  root_dir: output                      # Raw dataset location
  cached_dir: histograms                # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: img                             # Options: 'hist' for hist2noise or 'img' for noise2noise
  data_augmentation: true
  virt_size: 1000
  clean: true                           # Whether to include 'clean' targets if available
  aov: true                             # Whether to include 'aov' channels to input image (note: model in_channels is 9 if aov is true)
  debug: true
  hist_regeneration: false
  supervised: false                     # if true supervised else self supervised
  tonemap: none                         # 'log' or 'reinhard' or 'reinhard_gamma' or 'none'
  target_split: 16

model:
  in_channels: 9
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 4
  start_filters: 48  
  learning_rate: 1e-4

# General DataLoader settings
batch_size: 16
num_workers: 4
shuffle: true
pin_memory: false
standardisation: global                 # TODO: add support to toggle on/off log norm
loss: mse                               # 'rmse' or 'lhdr' when output is not tonemapped

# Validation split
val_split: 0.1                          # 10% validation split (bigger val better for model performance)

# Training
num_epochs: 20
save_dir: checkpoints
input_tonemap: none

# Additional CLI-style arguments (added at root level)
train_dir: train
valid_dir: valid
ckpt_save_path: ckpts
ckpt_overwrite: true
report_interval: 5
train_size: null
valid_size: null

# Training hyperparameters (CLI overrides)
learning_rate_cli: 0.001
adam: [0.9, 0.99, 1e-8]
batch_size_cli: 4
nb_epochs: 100
loss_cli: hdr

cuda: false
plot_stats: false

# Corruption parameters
noise_type: mc
noise_param: 50.0
seed: null
crop_size_cli: 128
clean_targets: false
