dataset:
  root_dir: output                        # Raw dataset location
  cached_dir: histograms                  # Cached histograms are saved
  crop_size: 128
  low_spp: 32
  high_spp: 4500
  hist_bins: 16
  mode: img                               # Options: 'hist' for hist2noise or 'img' for noise2noise
  data_augmentation: true
  virt_size: 8000
  clean: true                             # Whether to include 'clean' targets if available
  aov: true                               # Whether to include 'aov' channels to input image (note: model in_channels is 9 if aov is true)
  debug: true                             # if true saves one plot per epoch in a debug plot folder
  hist_regeneration: false
  supervised: false                       # if true supervised else self supervised
  tonemap: none                           # 'log' or 'reinhard' or 'reinhard_gamma' or 'none'
  target_split: 16

model:
  model_name: n2n
  in_channels: 9
  out_mode: mean                          # 'mean' or 'dist'
  merge_mode: concat                      # 'add' or 'concat'
  depth: 4
  start_filters: 48  
  learning_rate: 1e-4

# General DataLoader settings
batch_size: 16
num_workers: 10
shuffle: true
pin_memory: false
standardisation: global
loss: lhdr                                # 'rmse' or 'lhdr' when output is not tonemapped

val_split: 0.1                            # 10% validation split

# training
num_epochs: 300
save_dir: checkpoints
input_tonemap: none
