dataset:
  root_dir: output                        # Raw dataset location
  cached_dir: crops                       # Cached histograms are saved
  crop_size: 128
  crops_per_scene: 300                   # num of crops per scene to generate
  use_cached_crops: false
  low_spp: 64
  high_spp: 4500
  hist_bins: 32
  mode: stat                              # 'hist' for hist2noise or 'img' or 'stat' for noise2noise
  data_augmentation: true                 # horizontal and vertical flips
  clean: true                             # Whether to include 'clean' targets if available
  aov: true                               # Whether to include 'aov' channels to input image (note: model in_channels is 9 if aov is true)
  debug: true                             # if true saves one plot per epoch in a debug plot folder
  supervised: false                       # if true supervised else self supervised
  tonemap: none                           # tonemap applied to the loss: 'log' or 'reinhard' or 'reinhard_gamma' or 'none' 
  input_tonemap: log                      # tonemap applied to the input: 'log' or 'reinhard' or 'reinhard_gamma' or 'none' 
  target_split: 32

model:
  model_name: n2n                       # 'gap' or 'n2n'
  in_channels: 12                       # 3 (img) or 9 (img + aov) or 10 (stat + aov)
  out_mode: mean                        # 'mean' or 'dist'
  merge_mode: concat                    # 'add' or 'concat'
  depth: 4                              # only for GAP model
  start_filters: 48                     # only for GAP model
  learning_rate: 1e-4

# DATALOADER
batch_size: 16                          # minibatch: 8, 12, or 16
num_workers: 10                          # 4 on CPU or 8 on GPU
shuffle: true
pin_memory: false
standardisation: global                  # if 'global' print dataset mean and std
loss: smape                              # 'mse' or 'l1' or 'rel_mse' or 'root_mse' or 'lhdr' or 'smape'

val_split: 0.1                           # 10% validation split

# TRAINING
num_epochs: 300
plot_every: 5                            # how often to save the debug plots
save_dir: checkpoints